stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build_staging:
  image: docker:git
  stage: build
  environment: staging
  services:
  - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/reallybigtree/pinecone-server .
    - docker push registry.gitlab.com/reallybigtree/pinecone-server
  only:
    - develop

build_prod:
  image: docker:git
  stage: build
  environment: production
  services:
  - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/reallybigtree/pinecone-server .
    - docker push registry.gitlab.com/reallybigtree/pinecone-server
  only:
    - master